# Generated by Django 5.2 on 2025-05-02 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('type', models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='EXPENSE', max_length=7, verbose_name='Тип категорії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], max_length=7, verbose_name='Тип транзакції')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата транзакції')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.category', verbose_name='Категорія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
